### PR TITLE
Update minimist to fix security vulnerability

### PR DESCRIPTION
**Pull request by CristinaRO**
Fixes https://github.com/advisories/GHSA-vh95-rmgr-6w4m

Don't forget that it needs three approving reviews and at least two weeks of age... Hopefully someone can override this.

### CODE REVIEW

**Comment by erbridge** [comment]
The `tooling` tag should allow it to bypass the 2 weeks.

**Comment by CristinaRO** [comment]
> Is Dependabot not running on this repo for JavaScript?

🤷 I can't see a way to enable it, maybe it's a permissions thing as usual.

**Comment by rjw1** [comment]
> > Is Dependabot not running on this repo for JavaScript?
> 
> 🤷 I can't see a way to enable it, maybe it's a permissions thing as usual.

I've enabled it.

**Comment by pezholio** [comment]
In the spirit of keeping things tidy, I'm gonna merge this, which should then auto-close the Dependabot PR.

**Pull request merged**
